# This workflow will build the finished JAR with Maven and create a new release with it.

name: Build MonitorAPI JAR
on: [push]
permissions:
  actions: read
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: mvn clean package
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: target/MonitorAPI.jar
